---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: security-server-config
    image: centos:7
    command: "/lib/systemd/systemd"
    privileged: "True"
    groups:
      - test
      - dev
provisioner:
  name: ansible
  # playbooks:
  #   converge: ../../playbook.yml
  env:
    ANSIBLE_ROLES_PATH: "roles:../../../"
  # config_options:
  #   defaults:
  #     vault_password_file: "../../.vault"
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  options:
    junit-xml: junit.xml
  lint:
    name: flake8
