---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint -c .yamllint .
  ansible-lint .
platforms:
  - name: amazonlinux2
    image: amazonlinux:2
    # command: "/lib/systemd/systemd"
    privileged: True
    # tmpfs:
    #   - /run
    #   - /tmp
    # volumes:
    #   - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true
    groups:
      - test
      - dev
      - amazonlinux
  - name: centos7
    image: centos:7
    command: "/lib/systemd/systemd"
    privileged: True
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true
    groups:
      - test
      - dev
provisioner:
  name: ansible
  log: true
  inventory:
    group_vars:
      all:
        sec_svr_cfg_disable_anon_root_login: "True"
verifier:
  name: ansible
