---
- name: Prepare Amazonlinux
  hosts: amazonlinux2
  tasks:
    - name: Install systemd
      package:
        name: systemd
        state: present
- name: Prepare All
  hosts: all
  tasks:
    - name: Install procps
      package:
        name: procps-ng
        state: present
