---
name: Molecule
on:
  # push:
  #   branches:
  #     - refresh
  pull_request:
    branches:
      - master
jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: Ansible Molecule
        uses: gofrolist/molecule-action@v2.0.1
        with:
          molecule_command: test
          # molecule_args: "--all"
